### ISSUE TITLE
Missing dependency libffi

### ISSUE THREAD

**Issue by coreylane** [UnRAIDES/unRAID-NerdTools#37]
Running Unraid 6.11.5 w/ NerdTools 2022.11.01 - Appears to be missing dependency `libffi`. 

```
root@darktower:~# iotop
libffi.so.7: cannot open shared object file: No such file or directory
To run an uninstalled copy of iotop,
launch iotop.py in the top directory
```

**Comment by UnRAIDES** [comment]
Hi,
This is fixed on 2023/03/05 version.

Thank you.

**Comment by emaspa** [comment]
Not fixed, Unraid 6.11.5, updated nerdtools and all packages, rebooted.
![image](https://user-images.githubusercontent.com/18552276/222957399-1e7af87c-63ce-45eb-9ead-65ce7de16feb.png)
![image](https://user-images.githubusercontent.com/18552276/222957412-ec086358-bc5e-4a2e-b453-e9ed5f8ae0ae.png)

**Comment by emaspa** [comment]
Seems like reboot wasn't enough, had to uninstall and install the packages again in Nerdtools UI.

**Comment by Mcklaren** [comment]
Hello,
So it has been solved already ???
The problem is that libffi is a dependency of iotop so it must be installed at the same time.

**Comment by jsavargas** [comment]
I'm going to try my test unraid, see if I get the same error

**Comment by Mcklaren** [comment]
OK @Cronus89, thank you by your report. 

We're working en fixed the problem.

Best regards.

**Comment by coreylane** [comment]
This is resolved for me now, thanks! 

1. Uninstalled all NerdTools packages
2. Updated NerdTools plugin to `2023.03.11`
3. Re-installed packages like `iotop`
4. Confirmed `iotop` is working now

**Comment by jpmeijers** [comment]
After updating to Unraid 6.12.6 2023-12-01 I am getting the missing libffi.so.7 error again. I've updated to the latest NerdTools 2024.01.07, removed all the python packages, then intalled borgbackup-1.2.7-x86_64-1_SBo_UES.txz.

When I go to a terminal and type `pip install b2` it downloads the package, but errors out on the missing libffi.so.7.
```
ImportError while trying to load entry-point bdist_wheel: libffi.so.7: cannot open shared object file: No such file or directory
```

I've also tried installing `iotop-0.6-x86_64-2_SBo.txz` via NerdTools, but that also doesn't bring in libffi 7.

**Comment by Mcklaren** [comment]
> After updating to Unraid 6.12.6 2023-12-01 I am getting the missing libffi.so.7 error again. I've updated to the latest NerdTools 2024.01.07, removed all the python packages, then intalled borgbackup-1.2.7-x86_64-1_SBo_UES.txz.
> 
> When I go to a terminal and type `pip install b2` it downloads the package, but errors out on the missing libffi.so.7.
> 
> ```
> ImportError while trying to load entry-point bdist_wheel: libffi.so.7: cannot open shared object file: No such file or directory
> ```
> 
> I've also tried installing `iotop-0.6-x86_64-2_SBo.txz` via NerdTools, but that also doesn't bring in libffi 7.

I test iotop and I haven't problem. 

We have added version 3.3 but you have to use it at your own risk and before installing libffi-3.3 you have to delete the one that comes installed with unraid, for this you can use the command removepkg libffi-3.4.4.
